version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/confs:/etc/nginx/conf.d
    depends_on:
      - client
      - server
    restart: always
  client:
    build: ./docker/client
    volumes:
      - ./client:/app
  server:
    build: ./docker/server
    volumes:
      - ./server:/app